/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sorteiodados;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author 0063429
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    int item1 = 1;      
    int item2 = 1;   
    int item3 = 1;
    int item4 = 1;
    int item5 = 1;
    int item6 = 1;
    int item7 = 1;
    
     
    public FramePrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        labelImagem = new javax.swing.JLabel();
        Dado1 = new javax.swing.JLabel();
        Dado2 = new javax.swing.JLabel();
        Dado3 = new javax.swing.JLabel();
        Dado4 = new javax.swing.JLabel();
        Dado5 = new javax.swing.JLabel();
        Dado6 = new javax.swing.JLabel();
        qDado1 = new javax.swing.JLabel();
        qDado2 = new javax.swing.JLabel();
        qDado3 = new javax.swing.JLabel();
        qDado4 = new javax.swing.JLabel();
        qDado5 = new javax.swing.JLabel();
        qDado6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sorteio.png"))); // NOI18N
        jButton1.setText("Sorteio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Dado1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dado1.setText("Dado 1:");

        Dado2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dado2.setText("Dado 2:");

        Dado3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dado3.setText("Dado 3:");

        Dado4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dado4.setText("Dado 4:");

        Dado5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dado5.setText("Dado 5:");

        Dado6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Dado6.setText("Dado 6:");

        qDado1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qDado1.setText("0");

        qDado2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qDado2.setText("0");

        qDado3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qDado3.setText("0");

        qDado4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qDado4.setText("0");

        qDado5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qDado5.setText("0");

        qDado6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qDado6.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Dado2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dado3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dado4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dado5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dado6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qDado2)
                                    .addComponent(qDado3)
                                    .addComponent(qDado4)
                                    .addComponent(qDado5)
                                    .addComponent(qDado6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dado1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qDado1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButton1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dado2)
                            .addComponent(qDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dado3)
                            .addComponent(qDado3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dado4)
                            .addComponent(qDado4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dado5)
                            .addComponent(qDado5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dado6)
                            .addComponent(qDado6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Random gerador = new Random();
        
        int valorDado = gerador.nextInt(1, 7);
        
        labelImagem.setIcon(new ImageIcon(getClass()
                .getResource("/imagens/dado-" + valorDado + ".PNG")));
        
        if (valorDado == 1){
            qDado1.setText(" " + item1);
            item1 = +1;
            
        }
        
        if (valorDado == 2){
            qDado2.setText(" " + item2);
            item2 = +1;
        }
        
        if (valorDado == 3){
            qDado3.setText(" " + item3);
            item3 = +1;
        }
        
        if (valorDado == 4){
            qDado4.setText(" " + item4);
            item4 = +1;
        }
        
        if (valorDado == 5){
            qDado5.setText(" " + item5);
            item5 = +1;
        }
        
        if (valorDado == 6){
            qDado6.setText(" " + item6);
            item6 = +1;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dado1;
    private javax.swing.JLabel Dado2;
    private javax.swing.JLabel Dado3;
    private javax.swing.JLabel Dado4;
    private javax.swing.JLabel Dado5;
    private javax.swing.JLabel Dado6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel qDado1;
    private javax.swing.JLabel qDado2;
    private javax.swing.JLabel qDado3;
    private javax.swing.JLabel qDado4;
    private javax.swing.JLabel qDado5;
    private javax.swing.JLabel qDado6;
    // End of variables declaration//GEN-END:variables
}
